name: Publish NuGet Package

on:
  push:
    branches:
      - main

env:
  DOTNET_VERSION: '8.0.x'
  BUILD_CONFIGURATION: 'Release'
  PACKAGE_VERSION_MAJOR: '1'
  PACKAGE_VERSION_MINOR: '0'
  SOLUTION_FILE: 'Package.HealthCheck.sln'
  PACKAGE_PROJECT: 'Package.HealthCheck'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET Core SDK ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore ${{ env.SOLUTION_FILE }}

      - name: Build solution
        run: dotnet build ${{ env.SOLUTION_FILE }} --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

      - name: Generate Package Version
        id: version
        run: |
          BUILD_REV=$(echo $GITHUB_RUN_NUMBER)
          echo "PACKAGE_VERSION=${{ env.PACKAGE_VERSION_MAJOR }}.${{ env.PACKAGE_VERSION_MINOR }}.${BUILD_REV}" >> $GITHUB_ENV
          echo "Generated PACKAGE_VERSION=${{ env.PACKAGE_VERSION_MAJOR }}.${{ env.PACKAGE_VERSION_MINOR }}.${BUILD_REV}"

      - name: Pack NuGet Package
        run: dotnet pack ${{ env.PACKAGE_PROJECT }} --configuration ${{ env.BUILD_CONFIGURATION }} --no-build -p:PackageVersion=${{ env.PACKAGE_VERSION }}

      - name: Push NuGet Package to GitHub Packages
        run: dotnet nuget push "**/${{ env.PACKAGE_PROJECT }}/bin/${{ env.BUILD_CONFIGURATION }}/*.nupkg" --source "https://nuget.pkg.github.com/TAS-Tech-Dev/index.json" --api-key ${{ secrets.PAT_NUGET }}